### ISSUE TITLE
Doesn't work on some dtt files

### ISSUE THREAD

**Issue by Hikkooo** [ThisKwasior/KwasTools#1]
Dtt unpacker doesn't work on every ddt files in Metal Gear Rising. For example it doesn't unpack dtts which include font (For example the ev0000_us.dtt in ui folder.), only works for the Japanese ones though (For example the ev0000.dtt). I just drag and drop 'em and nothing happens.

Edit:  Removing "us" from the filename  worked.

**Comment by ThisKwasior** [comment]
Weird, but cool it worked
